using System.Globalization;
using CFHodEd.Math;
using GenericMesh.MaterialFields;
using GenericMesh.VertexFields;

namespace GenericMesh.Translators;

/// <summary>
/// Wavefront Object translator for reading and writing OBJ files.
/// </summary>
/// <remarks>
/// NOTE: The reader/writer are loosely implemented. Not all features of the 
/// wavefront object specification are implemented, and some are added as convenience.
/// </remarks>
public static class WavefrontObject
{
    /// <summary>Formatting for input/output (invariant culture).</summary>
    internal static readonly CultureInfo FormatProvider = CultureInfo.InvariantCulture;

    /// <summary>
    /// Writes a wavefront object file.
    /// </summary>
    public static void WriteFile<TVertex, TIndex, TMaterial>(
        string filename,
        GBasicMesh<TVertex, TIndex, TMaterial> mesh,
        bool breakIntoGroups = true,
        bool writeUVs = true,
        bool writeNormals = true,
        bool writeColourData = false,
        bool reverseUVs = false)
        where TVertex : struct, IVertex
        where TIndex : struct, IConvertible
        where TMaterial : struct, IMaterial
    {
        if (string.IsNullOrEmpty(filename))
            throw new ArgumentNullException(nameof(filename));
        if (mesh == null)
            throw new ArgumentNullException(nameof(mesh));

        string mtlFilename = Path.ChangeExtension(filename, ".mtl");
        
        using var writer = new StreamWriter(filename);
        
        // Write header
        writer.WriteLine("# Wavefront OBJ file");
        writer.WriteLine($"# Generated by GenericMesh");
        writer.WriteLine($"mtllib {Path.GetFileName(mtlFilename)}");
        writer.WriteLine();

        int vertexOffset = 0;
        int normalOffset = 0;
        int uvOffset = 0;

        // Write all parts
        for (int partIdx = 0; partIdx < mesh.PartCount; partIdx++)
        {
            var part = mesh.Part(partIdx);
            if (part == null) continue;

            string materialName = MaterialFieldReader.MaterialName(part.Material);
            if (string.IsNullOrEmpty(materialName))
                materialName = $"Material_{partIdx}";

            if (breakIntoGroups)
            {
                writer.WriteLine($"g Part_{partIdx}");
                writer.WriteLine($"usemtl {materialName}");
            }

            // Write vertices
            for (int i = 0; i < part.Vertices.Count; i++)
            {
                var vertex = part.Vertices[i];
                if (vertex is IVertexPosition3 pos)
                {
                    var p = pos.GetPosition3();
                    writer.WriteLine($"v {FloatToStr(p.X)} {FloatToStr(p.Y)} {FloatToStr(p.Z)}");
                }
            }

            // Write normals
            if (writeNormals)
            {
                for (int i = 0; i < part.Vertices.Count; i++)
                {
                    var vertex = part.Vertices[i];
                    if (vertex is IVertexNormal3 norm)
                    {
                        var n = norm.GetNormal3();
                        writer.WriteLine($"vn {FloatToStr(n.X)} {FloatToStr(n.Y)} {FloatToStr(n.Z)}");
                    }
                }
            }

            // Write UVs
            if (writeUVs)
            {
                for (int i = 0; i < part.Vertices.Count; i++)
                {
                    var vertex = part.Vertices[i];
                    if (vertex is IVertexTex2 tex)
                    {
                        var uv = tex.GetTexCoords2();
                        float v = reverseUVs ? (1.0f - uv.Y) : uv.Y;
                        writer.WriteLine($"vt {FloatToStr(uv.X)} {FloatToStr(v)}");
                    }
                }
            }

            // Write faces
            for (int pgIdx = 0; pgIdx < part.PrimitiveGroupCount; pgIdx++)
            {
                var pg = part.PrimitiveGroups(pgIdx);
                if (pg.Type != PrimitiveType.TriangleList)
                {
                    var copy = new GPrimitiveGroup<TIndex>(pg);
                    copy.ConvertToList();
                    WriteFaces(writer, copy, vertexOffset, normalOffset, uvOffset, writeNormals, writeUVs);
                }
                else
                {
                    WriteFaces(writer, pg, vertexOffset, normalOffset, uvOffset, writeNormals, writeUVs);
                }
            }

            vertexOffset += part.Vertices.Count;
            normalOffset += writeNormals ? part.Vertices.Count : 0;
            uvOffset += writeUVs ? part.Vertices.Count : 0;

            writer.WriteLine();
        }

        // Write material file
        WriteMtlFile(mtlFilename, mesh);
    }

    private static void WriteFaces<TIndex>(
        StreamWriter writer,
        GPrimitiveGroup<TIndex> pg,
        int vertexOffset,
        int normalOffset,
        int uvOffset,
        bool hasNormals,
        bool hasUVs)
        where TIndex : struct, IConvertible
    {
        for (int i = 0; i < pg.IndiceCount; i += 3)
        {
            int i0 = pg[i].ToInt32(null) + vertexOffset + 1;
            int i1 = pg[i + 1].ToInt32(null) + vertexOffset + 1;
            int i2 = pg[i + 2].ToInt32(null) + vertexOffset + 1;

            if (hasNormals && hasUVs)
            {
                int uv0 = pg[i].ToInt32(null) + uvOffset + 1;
                int uv1 = pg[i + 1].ToInt32(null) + uvOffset + 1;
                int uv2 = pg[i + 2].ToInt32(null) + uvOffset + 1;
                int n0 = pg[i].ToInt32(null) + normalOffset + 1;
                int n1 = pg[i + 1].ToInt32(null) + normalOffset + 1;
                int n2 = pg[i + 2].ToInt32(null) + normalOffset + 1;
                writer.WriteLine($"f {i0}/{uv0}/{n0} {i1}/{uv1}/{n1} {i2}/{uv2}/{n2}");
            }
            else if (hasNormals)
            {
                int n0 = pg[i].ToInt32(null) + normalOffset + 1;
                int n1 = pg[i + 1].ToInt32(null) + normalOffset + 1;
                int n2 = pg[i + 2].ToInt32(null) + normalOffset + 1;
                writer.WriteLine($"f {i0}//{n0} {i1}//{n1} {i2}//{n2}");
            }
            else if (hasUVs)
            {
                int uv0 = pg[i].ToInt32(null) + uvOffset + 1;
                int uv1 = pg[i + 1].ToInt32(null) + uvOffset + 1;
                int uv2 = pg[i + 2].ToInt32(null) + uvOffset + 1;
                writer.WriteLine($"f {i0}/{uv0} {i1}/{uv1} {i2}/{uv2}");
            }
            else
            {
                writer.WriteLine($"f {i0} {i1} {i2}");
            }
        }
    }

    private static void WriteMtlFile<TVertex, TIndex, TMaterial>(
        string filename,
        GBasicMesh<TVertex, TIndex, TMaterial> mesh)
        where TVertex : struct, IVertex
        where TIndex : struct, IConvertible
        where TMaterial : struct, IMaterial
    {
        using var writer = new StreamWriter(filename);
        
        writer.WriteLine("# MTL file");
        writer.WriteLine();

        for (int i = 0; i < mesh.PartCount; i++)
        {
            var part = mesh.Part(i);
            if (part == null) continue;

            string materialName = MaterialFieldReader.MaterialName(part.Material);
            if (string.IsNullOrEmpty(materialName))
                materialName = $"Material_{i}";

            string textureName = MaterialFieldReader.TextureName(part.Material);
            var attribs = MaterialFieldReader.Attributes(part.Material);

            writer.WriteLine($"newmtl {materialName}");
            writer.WriteLine("illum 2");
            writer.WriteLine($"Kd {FloatToStr(attribs.Diffuse.R)} {FloatToStr(attribs.Diffuse.G)} {FloatToStr(attribs.Diffuse.B)}");
            writer.WriteLine($"Ka {FloatToStr(attribs.Ambient.R)} {FloatToStr(attribs.Ambient.G)} {FloatToStr(attribs.Ambient.B)}");
            writer.WriteLine($"Ks {FloatToStr(attribs.Specular.R)} {FloatToStr(attribs.Specular.G)} {FloatToStr(attribs.Specular.B)}");
            writer.WriteLine($"Ke {FloatToStr(attribs.Emissive.R)} {FloatToStr(attribs.Emissive.G)} {FloatToStr(attribs.Emissive.B)}");
            writer.WriteLine($"Ns {attribs.SpecularSharpness}");

            if (!string.IsNullOrEmpty(textureName))
                writer.WriteLine($"map_Kd {textureName}");

            writer.WriteLine();
        }
    }

    private static string FloatToStr(float value)
    {
        return value.ToString("G6", FormatProvider);
    }

    /// <summary>
    /// Reads a wavefront object file.
    /// </summary>
    /// <remarks>
    /// Reading OBJ files is more complex and requires parsing vertices, normals, UVs,
    /// and face data. This is a placeholder for the full implementation.
    /// </remarks>
    public static void ReadFile<TVertex, TIndex, TMaterial>(
        string filename,
        GBasicMesh<TVertex, TIndex, TMaterial> outMesh,
        bool reverseUVs = false)
        where TVertex : struct, IVertex
        where TIndex : struct, IConvertible
        where TMaterial : struct, IMaterial
    {
        if (string.IsNullOrEmpty(filename))
            throw new ArgumentNullException(nameof(filename));
        if (outMesh == null)
            throw new ArgumentNullException(nameof(outMesh));

        // Read file into temporary storage
        var store = new ObjFileDataStore();
        store.ReadFile(filename, reverseUVs);
        
        // Convert to mesh
        store.CopyTo(outMesh);
    }
}

/// <summary>
/// Temporary storage for OBJ file data during parsing.
/// </summary>
internal class ObjFileDataStore
{
    public List<Vector3> Positions { get; } = new();
    public List<Vector3> Normals { get; } = new();
    public List<Vector2> UVs { get; } = new();
    public List<ObjGroup> Groups { get; } = new();
    public Dictionary<string, ObjMaterial> Materials { get; } = new();

    public void ReadFile(string filename, bool reverseUVs)
    {
        if (!File.Exists(filename))
            throw new FileNotFoundException("OBJ file not found.", filename);

        string? currentGroup = "default";
        string? currentMaterial = null;
        var currentFaces = new List<ObjFace>();
        
        string basePath = Path.GetDirectoryName(filename) ?? ".";

        foreach (var rawLine in File.ReadLines(filename))
        {
            string line = rawLine.Trim();
            if (string.IsNullOrEmpty(line) || line.StartsWith('#'))
                continue;

            string[] parts = line.Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length == 0) continue;

            switch (parts[0].ToLowerInvariant())
            {
                case "v" when parts.Length >= 4:
                    Positions.Add(new Vector3(
                        ParseFloat(parts[1]),
                        ParseFloat(parts[2]),
                        ParseFloat(parts[3])));
                    break;

                case "vn" when parts.Length >= 4:
                    Normals.Add(new Vector3(
                        ParseFloat(parts[1]),
                        ParseFloat(parts[2]),
                        ParseFloat(parts[3])));
                    break;

                case "vt" when parts.Length >= 3:
                    float u = ParseFloat(parts[1]);
                    float v = ParseFloat(parts[2]);
                    if (reverseUVs) v = 1.0f - v;
                    UVs.Add(new Vector2(u, v));
                    break;

                case "g" when parts.Length >= 2:
                    // Save current group
                    if (currentFaces.Count > 0)
                    {
                        Groups.Add(new ObjGroup(currentGroup!, currentMaterial, currentFaces.ToArray()));
                        currentFaces.Clear();
                    }
                    currentGroup = parts[1];
                    break;

                case "usemtl" when parts.Length >= 2:
                    currentMaterial = parts[1];
                    break;

                case "mtllib" when parts.Length >= 2:
                    string mtlPath = Path.Combine(basePath, parts[1]);
                    if (File.Exists(mtlPath))
                        ReadMtlFile(mtlPath);
                    break;

                case "f" when parts.Length >= 4:
                    var face = ParseFace(parts);
                    if (face != null)
                        currentFaces.Add(face);
                    break;
            }
        }

        // Save last group
        if (currentFaces.Count > 0)
            Groups.Add(new ObjGroup(currentGroup!, currentMaterial, currentFaces.ToArray()));
    }

    private void ReadMtlFile(string filename)
    {
        string? currentName = null;
        var diffuse = new ColorValue(0.8f, 0.8f, 0.8f, 1f);
        var ambient = new ColorValue(0.2f, 0.2f, 0.2f, 1f);
        var specular = new ColorValue(0f, 0f, 0f, 1f);
        var emissive = new ColorValue(0f, 0f, 0f, 1f);
        float shininess = 0;
        string? texture = null;

        foreach (var rawLine in File.ReadLines(filename))
        {
            string line = rawLine.Trim();
            if (string.IsNullOrEmpty(line) || line.StartsWith('#'))
                continue;

            string[] parts = line.Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length == 0) continue;

            switch (parts[0].ToLowerInvariant())
            {
                case "newmtl" when parts.Length >= 2:
                    if (currentName != null)
                    {
                        Materials[currentName] = new ObjMaterial(currentName, diffuse, ambient, specular, emissive, shininess, texture);
                    }
                    currentName = parts[1];
                    diffuse = new ColorValue(0.8f, 0.8f, 0.8f, 1f);
                    ambient = new ColorValue(0.2f, 0.2f, 0.2f, 1f);
                    specular = new ColorValue(0f, 0f, 0f, 1f);
                    emissive = new ColorValue(0f, 0f, 0f, 1f);
                    shininess = 0;
                    texture = null;
                    break;

                case "kd" when parts.Length >= 4:
                    diffuse = new ColorValue(ParseFloat(parts[1]), ParseFloat(parts[2]), ParseFloat(parts[3]), 1f);
                    break;

                case "ka" when parts.Length >= 4:
                    ambient = new ColorValue(ParseFloat(parts[1]), ParseFloat(parts[2]), ParseFloat(parts[3]), 1f);
                    break;

                case "ks" when parts.Length >= 4:
                    specular = new ColorValue(ParseFloat(parts[1]), ParseFloat(parts[2]), ParseFloat(parts[3]), 1f);
                    break;

                case "ke" when parts.Length >= 4:
                    emissive = new ColorValue(ParseFloat(parts[1]), ParseFloat(parts[2]), ParseFloat(parts[3]), 1f);
                    break;

                case "ns" when parts.Length >= 2:
                    shininess = ParseFloat(parts[1]);
                    break;

                case "map_kd" when parts.Length >= 2:
                    texture = parts[1];
                    break;
            }
        }

        if (currentName != null)
            Materials[currentName] = new ObjMaterial(currentName, diffuse, ambient, specular, emissive, shininess, texture);
    }

    private static ObjFace? ParseFace(string[] parts)
    {
        if (parts.Length < 4) return null;
        
        var indices = new List<ObjVertex>();
        for (int i = 1; i < parts.Length; i++)
        {
            string[] components = parts[i].Split('/');
            int v = ParseInt(components[0]) - 1;
            int vt = components.Length > 1 && !string.IsNullOrEmpty(components[1]) ? ParseInt(components[1]) - 1 : -1;
            int vn = components.Length > 2 && !string.IsNullOrEmpty(components[2]) ? ParseInt(components[2]) - 1 : -1;
            indices.Add(new ObjVertex(v, vt, vn));
        }
        return new ObjFace(indices.ToArray());
    }

    private static float ParseFloat(string s) =>
        float.TryParse(s, NumberStyles.Float, CultureInfo.InvariantCulture, out float result) ? result : 0f;

    private static int ParseInt(string s) =>
        int.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out int result) ? result : 0;

    public void CopyTo<TVertex, TIndex, TMaterial>(GBasicMesh<TVertex, TIndex, TMaterial> mesh)
        where TVertex : struct, IVertex
        where TIndex : struct, IConvertible
        where TMaterial : struct, IMaterial
    {
        // For each group, create a mesh part
        foreach (var group in Groups)
        {
            var part = new GMeshPart<TVertex, TIndex, TMaterial>();
            
            // Build unique vertices and indices
            var vertexMap = new Dictionary<ObjVertex, int>();
            var vertices = new List<TVertex>();
            var indices = new List<TIndex>();

            foreach (var face in group.Faces)
            {
                // Triangulate face (fan triangulation)
                for (int i = 1; i < face.Vertices.Length - 1; i++)
                {
                    AddVertex(face.Vertices[0], ref vertexMap, vertices, indices);
                    AddVertex(face.Vertices[i], ref vertexMap, vertices, indices);
                    AddVertex(face.Vertices[i + 1], ref vertexMap, vertices, indices);
                }
            }

            // Add vertices to part
            foreach (var v in vertices)
                part.Vertices.Append(new[] { v });

            // Create primitive group
            if (indices.Count > 0)
            {
                var pg = new GPrimitiveGroup<TIndex>();
                pg.Type = PrimitiveType.TriangleList;
                pg.Append(indices.ToArray());
                part.AddPrimitiveGroup(pg);
            }

            mesh.Add(part);
        }
    }

    private void AddVertex<TVertex, TIndex>(
        ObjVertex ov,
        ref Dictionary<ObjVertex, int> vertexMap,
        List<TVertex> vertices,
        List<TIndex> indices)
        where TVertex : struct, IVertex
        where TIndex : struct, IConvertible
    {
        if (!vertexMap.TryGetValue(ov, out int idx))
        {
            idx = vertices.Count;
            vertexMap[ov] = idx;
            
            TVertex vertex = new();
            vertex.Initialize();
            
            if (vertex is IVertexPosition3 pos && ov.Position >= 0 && ov.Position < Positions.Count)
                vertex = (TVertex)pos.SetPosition3(Positions[ov.Position]);
            
            if (vertex is IVertexNormal3 norm && ov.Normal >= 0 && ov.Normal < Normals.Count)
                vertex = (TVertex)norm.SetNormal3(Normals[ov.Normal]);
            
            if (vertex is IVertexTex2 tex && ov.UV >= 0 && ov.UV < UVs.Count)
                vertex = (TVertex)tex.SetTexCoords2(UVs[ov.UV]);
            
            vertices.Add(vertex);
        }
        
        indices.Add((TIndex)Convert.ChangeType(idx, typeof(TIndex)));
    }
}

internal record struct ObjVertex(int Position, int UV, int Normal);
internal record ObjFace(ObjVertex[] Vertices);
internal record ObjGroup(string Name, string? Material, ObjFace[] Faces);
internal record ObjMaterial(string Name, ColorValue Diffuse, ColorValue Ambient, ColorValue Specular, ColorValue Emissive, float Shininess, string? Texture);
