<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CFHodEd.UI</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.3" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.3" Condition="'$(Configuration)' == 'Debug'" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.21.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.21.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CFHodEd.Math\CFHodEd.Math.csproj" />
    <ProjectReference Include="..\CFHodEd.Rendering\CFHodEd.Rendering.csproj" />
    <ProjectReference Include="..\GenericMesh\GenericMesh.csproj" />
    <ProjectReference Include="..\HW2HOD\HW2HOD.csproj" />
    <ProjectReference Include="..\HW2IFF\HW2IFF.csproj" />
    <ProjectReference Include="..\HW2MAD\HW2MAD.csproj" />
    <ProjectReference Include="..\GMWavObjT\GMWavObjT.csproj" />
  </ItemGroup>
</Project>
